import { NextPage } from "next";
import Head from "next/head";
import FooterComponent from "../components/Footer/FooterComponent";
import HomeComponent from "../components/Home/HomeComponent";

 const Home: NextPage = (props) => {
  return (
    <div>
      <Head>
        <title>Yourgotocoder Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeComponent />
    </div>
  );
}

export default Home;

export async function getStaticProps(context) {
  return {
    props: {}, // will be passed to the page component as props
  }
}